name: MY DOCKER IMAGE GITHUB ACTION

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
>>>>>>> d917493aade4e4e8b864322f64c411fc85494b0b
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t demo .
