name: MY DOCKER IMAGE GITHUB ACTION

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$USERNAME" --password-stdin
          docker build -t my-image:latest .
