name: MY DOCKER IMAGE GITHUB ACTION

on:
  push:
    branches:
      - master

env:
  username: ${{ secrete.USERNAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> ba34de5e12b9161af53b5abcea9bcd0737339577
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: echo "$username and my password is $password"

