name: MY DOCKER IMAGE GITHUB ACTION

on:
  push:
    branches:
      - master

env:
  username: ${{ secrete.USERNAME }}
  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker login -u "$username and my password is $password"

